"""список избранного

Revision ID: 85c82b4d933b
Revises: 
Create Date: 2022-03-30 13:47:54.992491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c82b4d933b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_to_boats',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('captains', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['captains'], ['uboats.tactical_number'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.create_table('users_to_captains',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('captains', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['captains'], ['caps.name'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('users_to_captains')
    op.drop_table('users_to_boats')
    # ### end Alembic commands ###
